// @Library('terraformlibary')

// def terraforminfra = new org.opstree.terraform.groovy()

// node{
//   terraforminfra.call("Configuration")
// }
@Library('terraformlibary')_

node{
  terraform.call(vpc/Configuration)
}
